export const FETCH_COLLECTIONS_STARTED = "FETCH_COLLECTIONS_STARTED";
export const FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS";
export const FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTIONS_FAILURE";

export const FETCH_COLLECTION_STARTED = "FETCH_COLLECTION_STARTED";
export const FETCH_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS";
export const FETCH_COLLECTION_FAILURE = "FETCH_COLLECTION_FAILURE";

export const CREATE_COLLECTION_STARTED = "CREATE_COLLECTION_STARTED";
export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const CREATE_COLLECTION_FAILURE = "CREATE_COLLECTION_FAILURE";

export const EDIT_COLLECTION_STARTED = "EDIT_COLLECTION_STARTED";
export const EDIT_COLLECTION_SUCCESS = "EDIT_COLLECTION_SUCCESS";
export const EDIT_COLLECTION_FAILURE = "EDIT_COLLECTION_FAILURE";

export const DELETE_COLLECTION_STARTED = "DELETE_COLLECTION_STARTED";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_FAILURE = "DELETE_COLLECTION_FAILURE";
